stages:
  - build
  - test
  - deploy-aws
  - deploy-k8s

build:
  stage: build
  script:
    - docker build -t myapp:latest .
    - docker save myapp:latest | gzip > myapp.tar.gz
  artifacts:
    paths:
      - myapp.tar.gz

test:
  stage: test
  script:
    - echo "Running tests..."
    - # Add your test commands here

deploy-aws:
  stage: deploy-aws
  script:
    - terraform init
    - terraform apply -auto-approve

deploy-k8s:
  stage: deploy-k8s
  script:
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
